name: Generate Cargo Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build and generate documentation
        run: |
          cargo build --release
          cargo doc --target-dir=target/doc
      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: target/doc
