name: Generate Cargo Docs and Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-docs-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run tests
        run: |
          cd backend
          cargo test --all
      - name: Build and generate documentation
        run: |
          cd backend
          cargo build --release
          cargo doc --target-dir=../target/doc
      - name: Move documentation to gh-pages branch
        run: |
          git checkout gh-pages
          git mv target/doc .
          git add .
          git commit -m "Update documentation"
          git push
      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: .
          token: ${{ secrets.GH_PAT }}
