name: Generate Cargo Docs and Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-docs-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.3'  # Versão específica do Node.js

      - name: Install JSDoc
        run: |
          npm install -g jsdoc

      - name: Run tests
        run: |
          cd backend
          cargo test --all

      - name: Build and generate Cargo documentation
        run: |
          cd backend
          cargo build --release
          cargo doc --no-deps --target-dir=../docs/cargo

      - name: Generate JSDoc documentation
        run: |
          cd frontend
          jsdoc -c jsdoc.json -r -d ../docs/jsdoc

      - name: Create root index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Project Documentation</title>
          </head>
          <body>
              <h1>Project Documentation</h1>
              <ul>
                  <li><a href="cargo/scheduler/index.html">Rust Documentation</a></li>
                  <li><a href="jsdoc/index.html">React (JSDoc) Documentation</a></li>
              </ul>
          </body>
          </html>' > docs/index.html

      - name: Deploy documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
          token: ${{ secrets.GH_PAT }}
